"""Every number an overlay shows (cards, chips, charts written in index.html markup) must trace to the web-data file

STATUS: TESTED (hub; 52 numbers / 0 untraceable on the 26/09 ProfitBase index.html; here index.html = <comp>/index.html by default)
measured on the live app (paths.web_data), or be listed in numbers.derived with its formula/source.

Normalisation: drop currency/percent/x signs, '.' thousands (1.234.567 -> 1234567), ',' decimal -> '.'.
Only MARKUP is scanned (script/style blocks are removed) - numbers generated by JS at runtime are NOT seen: keep every
displayed number as literal markup (data-to="8879840") so this gate can read it (see references/qa-gates.md G3).

  python scripts/qa/check_numbers.py --config project.json   -> renders/qa/numbers-vs-webdata.txt, exit 1 if any not traceable
"""
import re
import sys
import pathlib

sys.path.insert(0, str(pathlib.Path(__file__).parent))
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))
from lib.sdv_common import load_config, out_dir  # noqa: E402

cfg, _ = load_config()
html = (cfg.rel(cfg.get2("qa.index_html")) if cfg.get2("qa.index_html") else cfg.comp("index.html")).read_text(encoding="utf-8")
web = cfg.p("web_data").read_text(encoding="utf-8")
DERIVED = cfg.get2("numbers.derived", {})
body = html[html.index("<body"):]
body = re.sub(r"<script\b.*?</script>", " ", body, flags=re.S)
body = re.sub(r"<style\b.*?</style>", " ", body, flags=re.S)
attr_nums = re.findall(r'data-to="([0-9.,]+)"', body)            # odometer targets live in attributes
text = re.sub(r"<[^>]+>", " ", body) + " " + " ".join(attr_nums)


def norm(n):
    n = re.sub(r"[₫đ%×x$€]", "", n).strip()
    if re.fullmatch(r"\d{1,3}(\.\d{3})+", n):
        return n.replace(".", "")
    return n.replace(",", ".").rstrip(".")


webnums = {norm(m) for m in re.findall(r"\d[\d.,]*", web)}
rows, bad = [], 0
for m in sorted(set(re.findall(r"\d[\d.,]*\d|\d", text)), key=lambda x: (len(x), x)):
    n = norm(m)
    ok = n in webnums or n.replace(".", "") in webnums
    why = "web-data" if ok else DERIVED.get(n, "")
    bad += not (ok or why)
    rows.append(f"{m:>14}  -> {n:<12} {'OK ' + why if (ok or why) else 'NOT FOUND'}")
out = out_dir(cfg) / "numbers-vs-webdata.txt"
out.write_text("\n".join(rows) + f"\n\nnumbers {len(rows)} | not traceable {bad}\n", encoding="utf-8")
print(f"numbers {len(rows)} | not traceable {bad}")
print("\n".join(r for r in rows if "NOT FOUND" in r))
sys.exit(1 if bad else 0)
